# Generated by Django 4.1.7 on 2023-02-16 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo_item',
            name='updated_at',
            field=models.DateTimeField(null=True),
        ),
    ]
