# Generated by Django 4.1.7 on 2023-02-16 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0002_alter_todo_item_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo_item',
            name='created_at',
            field=models.DateTimeField(auto_created=True, auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='todo_item',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
