# Generated by Django 4.1.7 on 2023-02-16 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0004_alter_todo_item_created_at'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Todo_item',
        ),
    ]
